### ISSUE TITLE
Openvpn .conf not found

### ISSUE THREAD

**Issue by finnlestrange** [theGuildHall/pwnbox#1]
When connected over a vpn the following error appears before by bash prompt, `cat: '/etc/openvpn/*.conf': No such file or directory` 
![image](https://user-images.githubusercontent.com/44287141/83396236-93c89d00-a3f3-11ea-90ae-e909bbecf81a.png)

To replicate the error I just followed all the instruction in the repo's readme

**Comment by finnlestrange** [comment]
Fixed by moving my .ovpn file to /etc/openvpn and change the extension from .ovpn to .conf

**Comment by theGuildHall** [comment]
thanks for the heads up!
