### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by hrtywhy** [theGuildHall/pwnbox#13]
![Screenshot at 2020-09-12 17-01-22](https://user-images.githubusercontent.com/44236850/92999561-55be3780-f511-11ea-92e5-78eaedc73cb4.png)

**Comment by theGuildHall** [comment]
Hi there,
Seems like there was an issue with you connecting to the HTB vpn. There could be a few reasons for this.

Check out this article to see if anything here is preventing you from connecting out: https://openvpn.net/faq/tls-error-tls-key-negotiation-failed-to-occur-within-60-seconds-check-your-network-connectivity/

You may need to regenerate your openvpn keys on HTB as well.
