### ISSUE TITLE
Weird bash prompt

### ISSUE THREAD

**Issue by Balajijangde** [theGuildHall/pwnbox#16]
when i start the terminal without connecting to vpn my prompt look like this
![local](https://user-images.githubusercontent.com/12787497/98391497-a1431c80-204e-11eb-9a64-b1eb5ccbfeb7.png)
and when i connected to vpn using systemctl start openvpn then my prompt looks like this
![vpn](https://user-images.githubusercontent.com/12787497/98391622-c768bc80-204e-11eb-96ec-712bd87a276e.png)
and my tmux looks more weirder
![tmux](https://user-images.githubusercontent.com/12787497/98391683-de0f1380-204e-11eb-926c-a249c88486a1.png)

**Comment by VadimBab1ch** [comment]
Same thing and I don't know how to fix...

**Comment by patrickhener** [comment]
Have the same problem as well. Any suggestions?

**Comment by navaneeth-dev** [comment]
Still facing this issue
