### ISSUE TITLE
No Zsh Shell in kali 

### ISSUE THREAD

**Issue by 0xtejas** [theGuildHall/pwnbox#17]
I followed the steps as mentioned int the readme.txt, I'm not getting the shell working once the openvpn is started
![image](https://user-images.githubusercontent.com/47889755/99791388-8f33a480-2b4b-11eb-878f-dacf2a9d1abd.png)

**Comment by 0xtejas** [comment]
I found the solution

**Comment by martinzeifang** [comment]
How did you solve it? I have the same Problem

**Comment by 0xtejas** [comment]
you have to put your vpn config file in `/etc/openvpn/`
