### ISSUE TITLE
Powershell Prompt

### ISSUE THREAD

**Issue by finnlestrange** [theGuildHall/pwnbox#2]
The powershell prompt is not customized like the bash prompt, I think this is a simple fix, Just take the following code and add it to `root/tmp/powershell/Microsoft.PowerShell_profile.ps1` like in PwnBox

![image](https://user-images.githubusercontent.com/44287141/83428529-76fb8c00-a42a-11ea-9d62-12a88a7c4dbf.png)

Here is what It should look like:
![image](https://user-images.githubusercontent.com/44287141/83428440-487db100-a42a-11ea-9ad1-bbf107f54aa7.png)

Here is the contents of the config file:
```
function vpnStats
{
    $htbip = (/opt/vpnbash.sh)
    if ($htbip -like '*10.*') {
        $vpnserver = (Get-Content /opt/vpnserver -First 1)
        return "`e[32m[`e[34m$vpnserver`e[32m]─[`e[37m$htbip`e[32m]─"
    } else {
        return ""
    }
}

function prompt
{
    Write-Host ("`e[1;32m┌─" + (vpnStats) + "`e[32m[`e[37m" + [Environment]::UserName + "`e[32m@`e[34m" + (hostname) + "`e[32m]─[`e[37m" + (Get-Location) + "`e[32m]")
    Write-Host ("`e[32m└──╼ [`e[34mPS`e[32m]>") -nonewline
    return " "
}

```

Hope this helps

**Comment by finnlestrange** [comment]
This config is also in `/etc/skel/.config/powershell/Microsoft.PowerShell_profile.ps1` on PwnBox
![image](https://user-images.githubusercontent.com/44287141/83429384-e2922900-a42b-11ea-821b-53d669237a9f.png)

**Comment by finnlestrange** [comment]
![image](https://user-images.githubusercontent.com/44287141/83431876-f50e6180-a42f-11ea-8d78-c34bece99d3c.png)
I can confirm that editing your powershell config located in `/home/username/.config/powershell/Microsoft.PowerShell_profile.ps1` does work

**Comment by theGuildHall** [comment]
Yup, you beat me to it. Found out where I had to add it. Give me a min and I'll update the instructions!

**Comment by finnlestrange** [comment]
Ahh no problem, I'll also link to this - [Here](https://www.smarthomebeginner.com/guide-configure-openvpn-autostart-linux/) which allows you to autostart your vpn on boot and makes it a system service, just like on pwn box, I'll include it here rather than make a new issue
