### ISSUE TITLE
vpnserver.sh wrong systemctl call

### ISSUE THREAD

**Issue by FriendlyButFire** [theGuildHall/pwnbox#20]
Hello, I followed a guide to set up my openVPN connection as a daemon at the start of the box:

Here is how i called the service:
![image](https://user-images.githubusercontent.com/20314571/111153556-65870900-8592-11eb-9fc8-a39ca13397ce.png)

How should I change the vpnserver.sh file? 

Things I tried:
-editing the commands in the file from openvpn@ to openvpn-client@ with no result

**Comment by theGuildHall** [comment]
Hi there,

You can change the vpnserver.sh file to this:

```bash
#!/bin/bash

vpn=$(cat `systemctl status openvpn-client@* | grep "/usr/sbin/openvpn" | tr -s " " | cut -d " " -f 12` | grep "remote " | cut -d " " -f 2)

if [[ $vpn == *"hackthebox"* ]]
then
    cat `systemctl status openvpn-client@* | grep "/usr/sbin/openvpn" | tr -s " " | cut -d " " -f 12` | grep "remote " | cut -d " " -f 2 | cut -d "." -f 1 | cut -d "-" -f 2-
else
    cat `systemctl status openvpn@* | grep "/usr/sbin/openvpn" | tr -s " " | cut -d " " -f 12` | grep "remote " | cut -d " " -f 2
fi
```

All I did was update the `systemctl status openvpn@*` to `systemctl status openvpn-client@*`. That should work

**Comment by FriendlyButFire** [comment]
> Hi there,
> 
> You can change the vpnserver.sh file to this:
> 
> ```shell
> #!/bin/bash
> 
> vpn=$(cat `systemctl status openvpn-client@* | grep "/usr/sbin/openvpn" | tr -s " " | cut -d " " -f 12` | grep "remote " | cut -d " " -f 2)
> 
> if [[ $vpn == *"hackthebox"* ]]
> then
>     cat `systemctl status openvpn-client@* | grep "/usr/sbin/openvpn" | tr -s " " | cut -d " " -f 12` | grep "remote " | cut -d " " -f 2 | cut -d "." -f 1 | cut -d "-" -f 2-
> else
>     cat `systemctl status openvpn@* | grep "/usr/sbin/openvpn" | tr -s " " | cut -d " " -f 12` | grep "remote " | cut -d " " -f 2
> fi
> ```
> 
> All I did was update the `systemctl status openvpn@*` to `systemctl status openvpn-client@*`. That should work

Edited; but still hanging up even on different terminal:

![image](https://user-images.githubusercontent.com/20314571/111271612-bb5ebe00-8631-11eb-99ce-2e50ce8d7cd6.png)

**Comment by FriendlyButFire** [comment]
Okay, fixed by deleting the file and replacing it with 

`#!/bin/bash
cat /etc/openvpn/*.conf | grep "remote " | cut -d " " -f 2 | cut -d "." -f 1 | cut -d "-" -f 2-`
