### ISSUE TITLE
Might want to add in the description that you have to be using Parrot 4.9 MATE

### ISSUE THREAD

**Issue by Raavtube** [theGuildHall/pwnbox#4]
I first followed this on KDE and got very upset until I saw that you have to download Parrot MATE

Here's the link: [https://download.parrot.sh/parrot/iso/4.9.1/Parrot-security-4.9.1_x64.iso](https://download.parrot.sh/parrot/iso/4.9.1/Parrot-security-4.9.1_x64.iso)

**Comment by theGuildHall** [comment]
Correct, it needs to be Parrot MATE. I'll clarify it in the instructions.
