### ISSUE TITLE
Solution for tmux 

### ISSUE THREAD

**Issue by dimostenis21** [theGuildHall/pwnbox#7]
So after hours of searching and trying different thinks I found that if type this
On your . tmux.conf
if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then tmux attach -t default || tmux new -s default fi

You'll have htb terminal ♥️

**Comment by theGuildHall** [comment]
Wondeful! I'll add it to the instructions. Thanks for the awesome find.

**Comment by dimostenis21** [comment]
@theGuildHall  ohh I'm so sorry bash_profile  . profile or bashrc not in tmux .Conf
