### ISSUE TITLE
terminal new issue

### ISSUE THREAD

**Issue by dimostenis21** [theGuildHall/pwnbox#9]
I dont have the star :| ![Screenshot_20200716_195644.png](https://user-images.githubusercontent.com/67795777/87701088-0de49380-c7a0-11ea-99f4-e46e1bee1819.png)

**Comment by theGuildHall** [comment]
can you post the contents of your .bashrc?

in mine, where the line starts `if [ "$color_prompt" = yes ]; then`, i have the below PS1 for my tmux which includes the star.

```bash
PS1="\[\033[1;32m\]\342\224\214\342\224\200$([[ $(/opt/vpnbash.sh) == *"10."* ]] && echo "[\[\033[1;34m\]$(/opt/vpnserver.sh)\[\033[1;32m\]]\342\224\200[\[\033[1;37m\]$(/opt/vpnbash.sh)\[\033[1;32m\]]\342\224\200")[\[\033[1;37m\]\u\[\033[01;32m\]@\[\033[01;34m\]\h\[\033[1;32m\]]\342\224\200[\[\033[1;37m\]\w\[\033[1;32m\]]\n\[\033[1;32m\]\342\224\224\342\224\200\342\224\200\342\225\274 [\[\e[01;33m\]??\[\e[01;32m\]]\\$ \[\e[0m\]"
```

**Comment by dimostenis21** [comment]
PS1="\[\033[1;32m\]\342\224\214\342\224\200$([[ $(/opt/vpnbash.sh) == *"10."* ]] && echo "[\[\033[1;34m\]$(/opt/vpnserver.sh)\[\033[1;32m\]]\342\224\200[\[\033[1;37m\]$(/opt/vpnbash.sh)\[\033[1;32m\]]\342\224\200")[\[\033[1;37m\]\u\[\033[01;32m\]@\[\033[01;34m\]\h\[\033[1;32m\]]\342\224\200[\[\033[1;37m\]\w\[\033[1;32m\]]\n\[\033[1;32m\]\342\224\224\342\224\200\342\224\200\342\225\274 [\[\e[01;33m\]??\[\e[01;32m\]]\\$ \[\e[0m\]"


I removed the ?? and copied a star text like this : ⭒ from internet and now is fine!
